### ISSUE TITLE
Improve DIS backend access controls

### ISSUE THREAD

**Issue by craigpratt** [cablelabs/ddos-info-sharing#4]

**Comment by darshakthakore** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Deprecate passing of DIS client API key as "api_key" query parameter #32](https://github.com/cablelabs/dis-arbor-monitor/issues/32)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/14013122) | N/A | craigpratt | running-tests | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Get information on how the NetReach Role system works - and determine if/how it can be ported #6](https://github.com/cablelabs/ddos-info-sharing/issues/6)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13861736) | N/A | Chadyshack, craigpratt | wont-fix | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [update_user_admin_status seems to be out of place/outdated #117](https://github.com/cablelabs/dis-backend/issues/117)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13846469) | N/A | N/A | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Create document to track items that rely on long term employee presence  #115](https://github.com/cablelabs/dis-backend/issues/115)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13846471) | N/A | N/A | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [IP Group list attack source information is only available to the identity that created it, should instead be org auth #57](https://github.com/cablelabs/dis-backend/issues/57)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13846488) | N/A | N/A | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Verify that all endpoints require auth that is necessary for the situation #50](https://github.com/cablelabs/dis-backend/issues/50)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13846492) | N/A | N/A | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [The example curl command on the DIS "Report Generation" page appears to have the wrong API token header #32](https://github.com/cablelabs/dis-frontend/issues/32)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13846963) | N/A | N/A | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Draft a charter for the DIS Steering Committee #7](https://github.com/cablelabs/ddos-info-sharing/issues/7)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13862275) | N/A | Chadyshack, craigpratt | Done | Closed
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Determine list of Roles and per-endpoint/verb role permissions #5](https://github.com/cablelabs/ddos-info-sharing/issues/5)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13861735) | N/A | Chadyshack | Done | Closed


###### do-not-edit-end-codetree-epic-issues
