### ISSUE TITLE
Event logging

### ISSUE THREAD

**Issue by craigpratt** [cablelabs/ddos-info-sharing#43]
This epic is to collect all tasks related to the logging of "events"

e.g. "account created", "account removed", "account role change", "report generated", "attack report uploaded", "source entries cleared" (with dates), etc.

**Comment by darshakthakore** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-closed.svg) [Record report generation requests #122](https://github.com/cablelabs/dis-backend/issues/122)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/YjxS/issues/13902385) | N/A | N/A | Done | Closed


###### do-not-edit-end-codetree-epic-issues
